DEFAULT_LIQUIDITY_CLIENT_RELAY_CHANNEL_OWNER = float('inf')
DEFAULT_LIQUIDITY_CLIENT_RELAY_CHANNEL_RELAY = float('inf')
LIQUIDITY_ASSUMPTION = True

# Need to update with more realistic values:
CHANNEL_COST = 5
CHANNEL_CREATION_FEE = 1
RELAY_TRANSACTION_FEE = 1

PATH_FIND_MAX_RETRY = 10
HOPS_NUMBER = 3

if __name__ == '__main__':
    pass

