CHANNEL_COST = 5
DEFAULT_LIQUIDITY_CLIENT_RELAY_CHANNEL_OWNER = float('inf')
DEFAULT_LIQUIDITY_CLIENT_RELAY_CHANNEL_RELAY = 100
CHANNEL_CREATION_FEE = 1
RELAY_TRANSACTION_FEE = 1
PATH_FIND_MAX_RETRY = 10
HOPS_NUMBER = 3
LIQUIDITY_ASSUMPTION = True

if __name__ == '__main__':
    pass

